### ISSUE TITLE
Nie działają skróty klawiszy

### ISSUE THREAD

**Issue by wooyek** [xinulsw/linetc#2]
C+Esc - menu start
W+f - menedżer plików (pcmanfm)
W+t - terminal (LXTerminal)
W+e - Geany IDE
W+p - PyCharm IDE
W+w - przeglądarka WWW (Palemoon)

**Comment by xinulsw** [comment]
Tak, masz rację, że ze skrótami jest problem. To dlatego, że klawiatura ustawiana jest domyślnie przez X serwer na pc101 zamiast pc105, czyli zawierającą dodatkowe klawisze. Spróbuj na razie rozwiązania podanego w instrukcji, czyli ręcznego określenia typu klawiatury. Spróbuję to coś zaumatyzować.
